# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/database/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
filter = { only_tables = [
    "pages",
    "peers",
    "users",
    "user_settings",
    "warnings",
    "torrents",
    "participants",
    "groups",
    "notifications",
    "tickets",
] }

[migrations_directory]
dir = "src/database/migrations"
